### ISSUE TITLE
05.06.2021 - 12.06.2021 tarixindəki taskların nəticəsi:

### ISSUE THREAD

**Issue by yasin-mehdiyev** [AghalarYusublu/PragmatechFrontendProject#1]
Çatışmazlıqlar:
  
     1)  Githuba push edərkən taska aydın şəkildə comment yaz.Git Commentlər yaxşı deyil(Görülən işlər barədə xırda bir comment
          yazsan daha məsləhətlidir.)
     2)  Variable adlarınının hamısını ingilis dilində camelCase şəklində yazsan daha məsləhətlidi. Example: let isNumber şəklində
     3)  5-ci taskında alqoritm tam düzgün yazılmayıb o tapşırığa yenidən nəzər yetir.Alqoritmi fərqli input datalarla test etsən bir 
          iki səhv olduğunu görəcəksən.
     4)  7-ci taskında underfined bugı var sonuncu element underfined çıxarır.

**Comment by AghalarYusublu** [comment]
1. Tamam
2. Tamam
3. ve 4. Sabah dersde baxilacaq

**Comment by AghalarYusublu** [comment]
tamamlandi.
