### ISSUE TITLE
12.06.2021-19.06.2021 tarixində verilmiş taskların code review nəticəsi:

### ISSUE THREAD

**Issue by yasin-mehdiyev** [AghalarYusublu/PragmatechFrontendProject#2]
1) **Clock Taskı** - View olaraq hər şey superdir. Kod tərəfdə də problem yoxdur. Sadəcə bir problem var. Müəllim tapşırığın 
       şərtində Html tərəfdə heç bir html kodu istifadə etmədən bütün elementlərin Js tərəfdə yazılmasını tələb edib.
2) **Portfolio taskı** demo version üçün yaxşıdır.
3) **Alqoritmik tapşırıqlar** - 3-cü alqoritm düzgün işləmir.Yenidən nəzər yetir(Rəqəmlərin cəmi olan taskdır)
4) _Github commentlər və variable adlandırmaları normaldır._

**Comment by AghalarYusublu** [comment]
1. Hocaya demişdik dedi istifadə etsez olar nəticə olsun.
4. Tamam həmin taska baxacam.
Təşəkkürlər .

23 Haz 2021 Çar 14:59 tarihinde yasin-mehdiyev ***@***.***>
şunu yazdı:
